### ISSUE TITLE
Could you add this variant to https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls ?

### ISSUE THREAD

**Issue by q2dg** [feilipu/Arduino_Goldilocks_Variant#1]
This would give more visibility to your project.
Thanks!

**Comment by feilipu** [comment]
Done. I think it is all correctly implemented. But independent confirmation would be welcome.

**Comment by per1234** [comment]
Unfortunately the folder structure of the Boards Manager installation archive file needs to be different from the way it is in this repository for Boards Manager installation to work. boards.txt, the bootloaders folder and the variants folder need to be in the root of the installation archive. To accomplish this you could just create the Boards Manager installation archive file manually and add it to each release or you could create a separate branch of the repository with the Boards Manager folder structure and then push any relevant changes to the master branch to the boards manager branch(for an example see https://github.com/SpenceKonde/ATTinyCore/tree/boardmanager.

**Comment by feilipu** [comment]
Hmm. Two different formats for one set of data... That seems very sensible.
Ok. I'll fix it properly over the weekend.

**Comment by feilipu** [comment]
Updated solution with everything now working.
