### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by per1234** [feilipu/Arduino_Goldilocks_Variant#2]
I am involved in a couple of bootloader projects([Ariadne](https://github.com/per1234/Ariadne-Bootloader) and [avr_boot](https://github.com/zevero/avr_boot)) and would like to be able to support Goldilocks and Goldilocks Analogue variants directly but to do that I'd need to use your pins_arduino.h files.

**Comment by feilipu** [comment]
Added a LGPL licence text.
If this is not sufficient, then please let me know.
Thanks.

**Comment by per1234** [comment]
Thank you!
