### ISSUE TITLE
is there hardware pcb schematic and pcb concern files?

### ISSUE THREAD

**Issue by youxiaojie** [feilipu/Arduino_Goldilocks_Variant#3]
is there hardware pcb schematic and pcb concern files?

**Comment by feilipu** [comment]
Yes. Should search "Goldilocks Analogue" and you will find all.

I don't recommend the earlier Goldilocks design because of issues using the 32U2 as a USB interface and timing difficulty with the 1284p. Best to use a FTDI for the USB interface as done in Goldilocks Analogue.

**Comment by feilipu** [comment]
The schematic and layout is in [this file](https://github.com/feilipu/Arduino_Goldilocks_Variant/blob/master/goldilocksanalogue_seeed_20151120.zip). 

The [User Manual](https://docs.google.com/document/d/1LGs2p1LJrhw7ILxYxPKPG6jSB6AaKTgUgrsZSF64VZM/edit).

**Comment by youxiaojie** [comment]
till now , I just find software, not find any pcb files. is it opensource hardware?

 timing? refers to the baud of 32u2 and 1284 has some difference led to problem in bootloader?

**Comment by feilipu** [comment]
Yes the boot loading is very timing sensitive. AVR at 16MHz has terrible serial timing offset, which is ok if both devices are equally wrong. But if one device is running at a frequency to generate correct serial rates the problems begin.

**Comment by feilipu** [comment]
Check the [Seeed zip file](https://github.com/feilipu/Arduino_Goldilocks_Variant/blob/master/goldilocksanalogue_seeed_20151120.zip) again. The hardware files are there.

**Comment by youxiaojie** [comment]
however the official uno take this design, I like! two mcu in one board. is the 32u2's firmware the same uno's?
and a question about crytal, I see different board take such as 16M, 16.384M, 11.0592M,32.768K, and you mentioned 22.1184Mhz.does take this binary like crystal is to improve the accuracy of the clock, usefull for rs232. does it effect the max running speed of the core? eg:22.1184 will lead to a 22.1184Mhz speed core? 16,384 will get a 16.384Mhz core? thanks! some puzzle with crystal choice and fuse setting:)

**Comment by feilipu** [comment]
The Goldilocks 32u2 firmware is LUFA. And it is in the repository.

The main MCU crystal directly affects performance and serial accuracy. 16MHz is several percent wrong. 22.1184MHz is perfectly correct.

http://ruemohr.org/~ircjunk/avr/baudcalc/avrbaudcalc-1.0.8.php

**Comment by feilipu** [comment]
Answered.
